name: pytorch3d-scene
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - async-timeout=3.0.1
  - attrs=20.3.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cachetools=4.2.1
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.4.7
  - cudatoolkit=10.1.243
  - freetype=2.10.4
  - fsspec=0.8.7
  - future=0.18.2
  - google-auth=1.26.1
  - google-auth-oauthlib=0.4.1
  - grpcio=1.33.2
  - idna=2.10
  - importlib-metadata=3.9.0
  - intel-openmp=2020.2
  - jpeg=9b
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - multidict=5.1.0
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pillow=8.1.2
  - pip=21.0.1
  - protobuf=3.14.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=2.0.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8.8
  - python_abi=3.8
  - pytorch=1.7.1
  - pytorch-lightning=1.2.5
  - pyyaml=5.3.1
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.2
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - tk=8.6.10
  - torchmetrics=0.2.0
  - torchvision=0.8.2
  - tqdm=4.59.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - werkzeug=1.0.1
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.5
